name: marketplace_entregador
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:

  image_cropper:
  image_picker:

  flutter_masked_text:

  email_validator:

  ##sgv
  flutter_svg:
  flutter_icons:

  flutter_secure_storage:

  ##ajuste do tamanho do texto
  auto_size_text:

  ## Google fonts
  google_fonts:

  ## Local Storage
  localstorage:

  ## conexão da internet
  connectivity:

  ## Lib de requisição
  dio:

  ## Lib de icones (Facebook e instagram)
  flutter_feather_icons: ^1.0.3
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^3.0.2+1
  rxdart: ^0.26.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_modular_test: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/