name: marketplace_store_app
description: Aplicativo marketplace aplicativo
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  jwt_decode:
  another_flushbar:
  cpf_cnpj_validator:
  search_cep:
  timelines:
  flutter_barcode_scanner:
  image_cropper:
  image_picker: 0.8.1+3

  flutter_masked_text2:

  email_validator:

  ##sgv
  flutter_svg:
  fluttericon:

  flutter_secure_storage:

  ##ajuste do tamanho do texto
  auto_size_text: 3.0.0-nullsafety.0

  ## Google fonts
  google_fonts: 2.1.0



  ## conexão da internet
  connectivity:

  ## Lib de requisição
  dio:

  ## Lib de icones (Facebook e instagram)
  flutter_feather_icons:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  flutter_modular: ^3.3.0
  rxdart:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_modular_test: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/